### ISSUE TITLE
Sample usage in C

### ISSUE THREAD

**Issue by feiyuxiaoThu** [aldma/qpdo#1]
I happened to read your work and found its efficiency in solving QP problems. I also clone this repo and find a matlab mex interface but how can I start usage in C? Thanks for your reply.

**Comment by aldma** [comment]
Hi, thank you for getting in touch!
In a new branch demo_C, I've added a demo for C in the examples/ folder, [demo_c.c](https://github.com/aldma/qpdo/blob/demo_C/examples/demo_c.c). It is heavily based on the example given for [QPALM](https://github.com/Benny44/QPALM/blob/master/examples/qpalm_demo.c). I haven't tried it yet.
